# Generated by Django 4.1.3 on 2022-12-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_settings', '0002_alter_unit_name_alter_unit_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_model_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=100, unique=True)),
                ('interval_type', models.CharField(choices=[('TSN', 'Time Since New'), ('TSR', 'Time Since Repair'), ('TSO', 'Time Since Overhaul'), ('TSI', 'Time Since Inspection')], default='TSN', max_length=3)),
                ('interval_day_count', models.IntegerField(blank=True, null=True)),
                ('interval_cycle_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity_name', models.CharField(max_length=100, unique=True)),
                ('ac_models', models.ManyToManyField(to='engineering.acmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('component_part_number', models.CharField(max_length=100)),
                ('effectivity', models.ManyToManyField(to='engineering.effectivity')),
            ],
        ),
        migrations.CreateModel(
            name='RepairablePN',
            fields=[
                ('pn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engineering.pn')),
                ('is_serialized', models.BooleanField()),
            ],
            bases=('engineering.pn',),
        ),
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=10, unique=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('ac_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.acmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RotablePN',
            fields=[
                ('pn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engineering.pn')),
                ('components', models.ManyToManyField(related_name='+', to='engineering.pn')),
                ('controls', models.ManyToManyField(to='engineering.control')),
            ],
            bases=('engineering.pn',),
        ),
        migrations.CreateModel(
            name='ExpandablePN',
            fields=[
                ('pn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engineering.pn')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.unit')),
            ],
            bases=('engineering.pn',),
        ),
    ]
