# Generated by Django 4.1.3 on 2022-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectivity',
            name='ac_models',
        ),
        migrations.AddField(
            model_name='effectivity',
            name='ac',
            field=models.ManyToManyField(to='engineering.ac'),
        ),
    ]
