# Generated by Django 4.1.3 on 2022-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_alter_unit_name_alter_unit_unit'),
        ('engineering', '0002_remove_effectivity_ac_models_effectivity_ac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpandablePN',
            new_name='ExpendablePN',
        ),
        migrations.AddField(
            model_name='pn',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
